"""005_phase_4_decision_reviews

Revision ID: 1b69f87c7cc0
Revises: a823ce790602
Create Date: 2026-09-01 19:06:04.878256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b69f87c7cc0'
down_revision: Union[str, Sequence[str], None] = 'a823ce790602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_decisions', sa.Column('review_status', sa.String(length=32), nullable=False, server_default='PENDING_HUMAN_REVIEW'))
    op.add_column('agent_decisions', sa.Column('reviewer_name', sa.String(length=128), nullable=True))
    op.add_column('agent_decisions', sa.Column('review_action', sa.String(length=64), nullable=True))
    op.add_column('agent_decisions', sa.Column('review_comment', sa.Text(), nullable=True))
    op.add_column('agent_decisions', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_agent_decisions_review_status', 'agent_decisions', ['review_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_decisions_review_status', table_name='agent_decisions')
    op.drop_column('agent_decisions', 'reviewed_at')
    op.drop_column('agent_decisions', 'review_comment')
    op.drop_column('agent_decisions', 'review_action')
    op.drop_column('agent_decisions', 'reviewer_name')
    op.drop_column('agent_decisions', 'review_status')
    # ### end Alembic commands ###
