"""001_phase_2b_initial_tables

Revision ID: 2f0fcc25451a
Revises: 
Create Date: 2026-08-31 22:52:56.812752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f0fcc25451a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('manufacturer', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('operational_status', sa.String(length=32), nullable=False),
    sa.Column('warranty_start', sa.Date(), nullable=True),
    sa.Column('warranty_end', sa.Date(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_id'), 'assets', ['asset_id'], unique=True)
    op.create_index(op.f('ix_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_operational_status'), 'assets', ['operational_status'], unique=False)
    op.create_table('incident_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('component_type', sa.String(length=64), nullable=False),
    sa.Column('defect_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_records_component_type'), 'incident_records', ['component_type'], unique=False)
    op.create_index(op.f('ix_incident_records_defect_type'), 'incident_records', ['defect_type'], unique=False)
    op.create_index(op.f('ix_incident_records_incident_id'), 'incident_records', ['incident_id'], unique=True)
    op.create_index(op.f('ix_incident_records_occurred_at'), 'incident_records', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_incident_records_severity'), 'incident_records', ['severity'], unique=False)
    op.create_table('components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('component_id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('component_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('material', sa.String(length=64), nullable=True),
    sa.Column('location_description', sa.String(length=256), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_asset_id'), 'components', ['asset_id'], unique=False)
    op.create_index(op.f('ix_components_component_id'), 'components', ['component_id'], unique=True)
    op.create_index(op.f('ix_components_component_type'), 'components', ['component_type'], unique=False)
    op.create_index(op.f('ix_components_status'), 'components', ['status'], unique=False)
    op.create_table('inspection_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', sa.String(length=64), nullable=False),
    sa.Column('component_id', sa.String(length=64), nullable=False),
    sa.Column('inspection_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inspection_method', sa.String(length=64), nullable=False),
    sa.Column('defect_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=False),
    sa.Column('evidence_reference', sa.String(length=256), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.component_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_records_component_id'), 'inspection_records', ['component_id'], unique=False)
    op.create_index(op.f('ix_inspection_records_defect_type'), 'inspection_records', ['defect_type'], unique=False)
    op.create_index(op.f('ix_inspection_records_inspection_id'), 'inspection_records', ['inspection_id'], unique=True)
    op.create_index(op.f('ix_inspection_records_inspection_timestamp'), 'inspection_records', ['inspection_timestamp'], unique=False)
    op.create_index(op.f('ix_inspection_records_severity'), 'inspection_records', ['severity'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('maintenance_id', sa.String(length=64), nullable=False),
    sa.Column('component_id', sa.String(length=64), nullable=False),
    sa.Column('maintenance_type', sa.String(length=64), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=False),
    sa.Column('technician_team', sa.String(length=128), nullable=False),
    sa.Column('downtime_hours', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.component_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_component_id'), 'maintenance_records', ['component_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_maintenance_id'), 'maintenance_records', ['maintenance_id'], unique=True)
    op.create_index(op.f('ix_maintenance_records_maintenance_type'), 'maintenance_records', ['maintenance_type'], unique=False)
    op.create_index(op.f('ix_maintenance_records_performed_at'), 'maintenance_records', ['performed_at'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', sa.String(length=64), nullable=False),
    sa.Column('component_id', sa.String(length=64), nullable=False),
    sa.Column('inspection_id', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('assigned_team', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('downtime_hours', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.component_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_component_id'), 'work_orders', ['component_id'], unique=False)
    op.create_index(op.f('ix_work_orders_inspection_id'), 'work_orders', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_work_orders_priority'), 'work_orders', ['priority'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    op.create_index(op.f('ix_work_orders_work_order_id'), 'work_orders', ['work_order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_work_order_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_priority'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_inspection_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_component_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_maintenance_records_performed_at'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_maintenance_type'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_maintenance_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_component_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_inspection_records_severity'), table_name='inspection_records')
    op.drop_index(op.f('ix_inspection_records_inspection_timestamp'), table_name='inspection_records')
    op.drop_index(op.f('ix_inspection_records_inspection_id'), table_name='inspection_records')
    op.drop_index(op.f('ix_inspection_records_defect_type'), table_name='inspection_records')
    op.drop_index(op.f('ix_inspection_records_component_id'), table_name='inspection_records')
    op.drop_table('inspection_records')
    op.drop_index(op.f('ix_components_status'), table_name='components')
    op.drop_index(op.f('ix_components_component_type'), table_name='components')
    op.drop_index(op.f('ix_components_component_id'), table_name='components')
    op.drop_index(op.f('ix_components_asset_id'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_incident_records_severity'), table_name='incident_records')
    op.drop_index(op.f('ix_incident_records_occurred_at'), table_name='incident_records')
    op.drop_index(op.f('ix_incident_records_incident_id'), table_name='incident_records')
    op.drop_index(op.f('ix_incident_records_defect_type'), table_name='incident_records')
    op.drop_index(op.f('ix_incident_records_component_type'), table_name='incident_records')
    op.drop_table('incident_records')
    op.drop_index(op.f('ix_assets_operational_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
