"""004_phase_3b_agent_decisions

Revision ID: a823ce790602
Revises: ea3b36453e6e
Create Date: 2026-09-01 18:20:06.985042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a823ce790602'
down_revision: Union[str, Sequence[str], None] = 'ea3b36453e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('inspection_id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('operational_decision', sa.String(length=64), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('decision_rationale', sa.Text(), nullable=False),
    sa.Column('human_review_required', sa.Boolean(), nullable=False),
    sa.Column('evidence_reference', sa.JSON(), nullable=False),
    sa.Column('risk_assessment', sa.JSON(), nullable=False),
    sa.Column('work_order', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('evidence_gaps', sa.JSON(), nullable=False),
    sa.Column('execution_metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_decisions_asset_id'), 'agent_decisions', ['asset_id'], unique=False)
    op.create_index('ix_agent_decisions_asset_op', 'agent_decisions', ['asset_id', 'operational_decision'], unique=False)
    op.create_index(op.f('ix_agent_decisions_decision_id'), 'agent_decisions', ['decision_id'], unique=True)
    op.create_index(op.f('ix_agent_decisions_inspection_id'), 'agent_decisions', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_agent_decisions_operational_decision'), 'agent_decisions', ['operational_decision'], unique=False)
    op.create_table('agent_reasoning_traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=True),
    sa.Column('input_summary', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('decision_impact', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['agent_decisions.decision_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_reasoning_traces_decision_id'), 'agent_reasoning_traces', ['decision_id'], unique=False)
    op.create_index(op.f('ix_agent_reasoning_traces_stage'), 'agent_reasoning_traces', ['stage'], unique=False)
    op.create_index(op.f('ix_agent_reasoning_traces_trace_id'), 'agent_reasoning_traces', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_reasoning_traces_trace_id'), table_name='agent_reasoning_traces')
    op.drop_index(op.f('ix_agent_reasoning_traces_stage'), table_name='agent_reasoning_traces')
    op.drop_index(op.f('ix_agent_reasoning_traces_decision_id'), table_name='agent_reasoning_traces')
    op.drop_table('agent_reasoning_traces')
    op.drop_index(op.f('ix_agent_decisions_operational_decision'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_inspection_id'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_decision_id'), table_name='agent_decisions')
    op.drop_index('ix_agent_decisions_asset_op', table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_asset_id'), table_name='agent_decisions')
    op.drop_table('agent_decisions')
    # ### end Alembic commands ###
