"""002_phase_2d_review_tables

Revision ID: a8974b65cbde
Revises: 2f0fcc25451a
Create Date: 2026-08-31 23:20:29.554230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8974b65cbde'
down_revision: Union[str, Sequence[str], None] = '2f0fcc25451a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_reviews',
    sa.Column('review_id', sa.String(length=64), nullable=False),
    sa.Column('inspection_id', sa.String(length=64), nullable=False),
    sa.Column('component_id', sa.String(length=64), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('reviewer_id', sa.String(length=64), nullable=True),
    sa.Column('reviewer_name', sa.String(length=128), nullable=True),
    sa.Column('reviewer_comments', sa.Text(), nullable=True),
    sa.Column('original_vision_evidence', sa.JSON(), nullable=False),
    sa.Column('original_decision', sa.JSON(), nullable=False),
    sa.Column('original_assessment', sa.JSON(), nullable=False),
    sa.Column('original_draft_work_order', sa.JSON(), nullable=False),
    sa.Column('reasoning_trace', sa.JSON(), nullable=False),
    sa.Column('edited_work_order', sa.JSON(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.component_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_inspection_reviews_assessment_id'), 'inspection_reviews', ['assessment_id'], unique=False)
    op.create_index('ix_inspection_reviews_comp_status', 'inspection_reviews', ['component_id', 'status'], unique=False)
    op.create_index(op.f('ix_inspection_reviews_component_id'), 'inspection_reviews', ['component_id'], unique=False)
    op.create_index(op.f('ix_inspection_reviews_inspection_id'), 'inspection_reviews', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_inspection_reviews_priority'), 'inspection_reviews', ['priority'], unique=False)
    op.create_index(op.f('ix_inspection_reviews_review_id'), 'inspection_reviews', ['review_id'], unique=False)
    op.create_index(op.f('ix_inspection_reviews_status'), 'inspection_reviews', ['status'], unique=False)
    op.create_table('review_audit_logs',
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('review_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('reviewer_id', sa.String(length=64), nullable=True),
    sa.Column('reviewer_name', sa.String(length=128), nullable=True),
    sa.Column('previous_status', sa.String(length=32), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('metadata_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['inspection_reviews.review_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_review_audit_logs_audit_id'), 'review_audit_logs', ['audit_id'], unique=False)
    op.create_index(op.f('ix_review_audit_logs_event_type'), 'review_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_review_audit_logs_review_id'), 'review_audit_logs', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_audit_logs_review_id'), table_name='review_audit_logs')
    op.drop_index(op.f('ix_review_audit_logs_event_type'), table_name='review_audit_logs')
    op.drop_index(op.f('ix_review_audit_logs_audit_id'), table_name='review_audit_logs')
    op.drop_table('review_audit_logs')
    op.drop_index(op.f('ix_inspection_reviews_status'), table_name='inspection_reviews')
    op.drop_index(op.f('ix_inspection_reviews_review_id'), table_name='inspection_reviews')
    op.drop_index(op.f('ix_inspection_reviews_priority'), table_name='inspection_reviews')
    op.drop_index(op.f('ix_inspection_reviews_inspection_id'), table_name='inspection_reviews')
    op.drop_index(op.f('ix_inspection_reviews_component_id'), table_name='inspection_reviews')
    op.drop_index('ix_inspection_reviews_comp_status', table_name='inspection_reviews')
    op.drop_index(op.f('ix_inspection_reviews_assessment_id'), table_name='inspection_reviews')
    op.drop_table('inspection_reviews')
    # ### end Alembic commands ###
