"""003_phase_3a_asset_analytics

Revision ID: ea3b36453e6e
Revises: a8974b65cbde
Create Date: 2026-08-31 23:31:36.375374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3b36453e6e'
down_revision: Union[str, Sequence[str], None] = 'a8974b65cbde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('defect_id', sa.String(length=64), nullable=False),
    sa.Column('inspection_id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('component_id', sa.String(length=64), nullable=True),
    sa.Column('defect_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('affected_area_percentage', sa.Float(), nullable=True),
    sa.Column('bounding_box_area_percentage', sa.Float(), nullable=True),
    sa.Column('crack_length_pixels', sa.Float(), nullable=True),
    sa.Column('crack_width_estimate_pixels', sa.Float(), nullable=True),
    sa.Column('location_type', sa.String(length=64), nullable=True),
    sa.Column('detection_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_evidence_detection_id', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_id'], ['components.component_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defect_records_asset_id'), 'defect_records', ['asset_id'], unique=False)
    op.create_index('ix_defect_records_asset_time', 'defect_records', ['asset_id', 'detection_timestamp'], unique=False)
    op.create_index(op.f('ix_defect_records_component_id'), 'defect_records', ['component_id'], unique=False)
    op.create_index(op.f('ix_defect_records_defect_id'), 'defect_records', ['defect_id'], unique=True)
    op.create_index(op.f('ix_defect_records_defect_type'), 'defect_records', ['defect_type'], unique=False)
    op.create_index(op.f('ix_defect_records_detection_timestamp'), 'defect_records', ['detection_timestamp'], unique=False)
    op.create_index(op.f('ix_defect_records_inspection_id'), 'defect_records', ['inspection_id'], unique=False)
    op.create_index('ix_defect_records_type_time', 'defect_records', ['defect_type', 'detection_timestamp'], unique=False)
    op.add_column('assets', sa.Column('asset_code', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=False)
    op.add_column('inspection_reviews', sa.Column('asset_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_inspection_reviews_asset_id'), 'inspection_reviews', ['asset_id'], unique=False)
    op.create_index('ix_inspection_reviews_asset_status', 'inspection_reviews', ['asset_id', 'status'], unique=False)
    op.create_foreign_key(None, 'inspection_reviews', 'assets', ['asset_id'], ['asset_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspection_reviews', type_='foreignkey')
    op.drop_index('ix_inspection_reviews_asset_status', table_name='inspection_reviews')
    op.drop_index(op.f('ix_inspection_reviews_asset_id'), table_name='inspection_reviews')
    op.drop_column('inspection_reviews', 'asset_id')
    op.drop_index(op.f('ix_assets_asset_code'), table_name='assets')
    op.drop_column('assets', 'asset_code')
    op.drop_index('ix_defect_records_type_time', table_name='defect_records')
    op.drop_index(op.f('ix_defect_records_inspection_id'), table_name='defect_records')
    op.drop_index(op.f('ix_defect_records_detection_timestamp'), table_name='defect_records')
    op.drop_index(op.f('ix_defect_records_defect_type'), table_name='defect_records')
    op.drop_index(op.f('ix_defect_records_defect_id'), table_name='defect_records')
    op.drop_index(op.f('ix_defect_records_component_id'), table_name='defect_records')
    op.drop_index('ix_defect_records_asset_time', table_name='defect_records')
    op.drop_index(op.f('ix_defect_records_asset_id'), table_name='defect_records')
    op.drop_table('defect_records')
    # ### end Alembic commands ###
