"""Pydantic v2 schemas for the Agentic Inspection Decision Engine (Phase 3B/3C/4)."""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field


class TraceEvent(BaseModel):
    """Structured observable trace event for an agent reasoning step."""
    step: int = Field(..., ge=1, description="Sequential execution step number")
    stage: str = Field(..., description="Stage identifier (e.g. INGEST_EVIDENCE, GET_ASSET_CONTEXT)")
    tool: Optional[str] = Field(default=None, description="Invoked tool name if applicable")
    input_summary: Optional[Dict[str, Any]] = Field(default=None, description="Sanitized input summary")
    result_summary: Optional[str] = Field(default=None, description="Human-readable outcome summary")
    decision_impact: Optional[str] = Field(default=None, description="How this step influenced the decision")
    status: str = Field(default="completed", description="Status: completed, failed, skipped")
    duration_ms: Optional[float] = Field(default=None, description="Step execution time in milliseconds")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = ConfigDict(extra="forbid")


class WorkOrderRecommendation(BaseModel):
    """Strongly typed maintenance work order recommendation generated by the agent."""
    work_order_id: str
    inspection_id: str
    asset_id: str
    component_id: Optional[str] = None
    priority: str = Field(..., description="CRITICAL, HIGH, MEDIUM, LOW")
    defect_type: str
    severity: str
    risk_level: str
    recommended_action: str
    justification: str
    required_inspection_methods: List[str] = Field(default_factory=list)
    estimated_cost: Optional[float] = Field(default=None, description="Estimated cost if available from historical baseline, else null")
    estimated_downtime_hours: Optional[float] = Field(default=None, description="Estimated downtime hours if available from historical baseline, else null")
    cost_notes: Optional[str] = Field(default=None, description="Explanation if cost or downtime is unavailable")
    recommended_team: str = "Pipeline Structural Integrity Team"
    safety_notes: List[str] = Field(default_factory=list)
    evidence_references: Dict[str, Any] = Field(default_factory=dict)
    generated_by: str = "Autonomous Inspection Decision Agent (Gemma 3)"
    generation_timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    status: str = Field(default="PENDING_HUMAN_REVIEW", description="Initial lifecycle state: always PENDING_HUMAN_REVIEW")

    model_config = ConfigDict(extra="forbid")


class AgentInspectionDecision(BaseModel):
    """Complete authoritative output contract for the Agentic Inspection Decision Engine."""
    schema_version: str = "1.0"
    decision_id: str
    inspection_id: str
    asset_id: str
    evidence_reference: Dict[str, Any]
    risk_assessment: Dict[str, Any]
    operational_decision: str  # "URGENT_ENGINEERING_REVIEW", "PRIORITY_MAINTENANCE", "PLAN_MAINTENANCE", "SCHEDULE_INSPECTION", "MONITOR", "INSUFFICIENT_EVIDENCE"
    decision_rationale: str
    work_order: Optional[WorkOrderRecommendation] = None
    reasoning_trace: List[TraceEvent] = Field(default_factory=list)
    evidence_gaps: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)
    human_review_required: bool = Field(default=True, description="Strict safety guardrail: always true for maintenance-affecting actions")
    
    # Human Review Workflow Metadata (Phase 4)
    review_status: str = Field(default="PENDING_HUMAN_REVIEW", description="Review state: PENDING_HUMAN_REVIEW, APPROVED, REJECTED, REQUEST_FURTHER_INSPECTION")
    reviewer_name: Optional[str] = Field(default=None, description="Authorized human inspector name")
    review_action: Optional[str] = Field(default=None, description="Human decision: APPROVED, REJECTED, REQUEST_FURTHER_INSPECTION")
    review_comment: Optional[str] = Field(default=None, description="Inspector audit remarks")
    reviewed_at: Optional[datetime] = Field(default=None, description="Timestamp of human authorization")

    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    execution_metrics: Dict[str, Any] = Field(default_factory=dict)

    model_config = ConfigDict(extra="forbid")


class AgentDecisionSummary(BaseModel):
    """Normalized summary record for decision queues and history tables."""
    decision_id: str
    inspection_id: str
    asset_id: str
    operational_decision: str
    risk_score: int
    risk_level: str
    review_status: str
    defect_count: int
    created_at: datetime
    reviewed_at: Optional[datetime] = None

    model_config = ConfigDict(extra="forbid")


class AgentDecisionListResponse(BaseModel):
    """Paginated list response for inspection decision history."""
    total: int
    items: List[AgentDecisionSummary] = Field(default_factory=list)

    model_config = ConfigDict(extra="forbid")


class AgentDecisionReviewRequest(BaseModel):
    """Request payload for human inspector review action."""
    reviewer_name: str = Field(..., min_length=1, description="Inspector name / employee ID")
    review_action: str = Field(..., description="Action: APPROVED, REJECTED, REQUEST_FURTHER_INSPECTION")
    review_comment: Optional[str] = Field(default=None, description="Inspector review notes")

    model_config = ConfigDict(extra="forbid")


class AgentInspectRequest(BaseModel):
    """API request payload for triggering autonomous inspection assessment."""
    inspection_id: str
    asset_id: str
    component_id: Optional[str] = None
    evidence: Dict[str, Any]

    model_config = ConfigDict(extra="forbid")
