"""Pydantic v2 schemas for Human Review Outcome Memory & Intelligence (Phase 7A)."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field


class ReviewOutcomeStatus(str, Enum):
    """Explicit human inspector review outcome status."""
    APPROVED = "APPROVED"
    CORRECTED = "CORRECTED"
    REJECTED = "REJECTED"


class EvidenceQuality(str, Enum):
    """Inspector assessment of input visual evidence quality."""
    EXCELLENT = "EXCELLENT"
    ADEQUATE = "ADEQUATE"
    MARGINAL = "MARGINAL"
    INSUFFICIENT = "INSUFFICIENT"


class ConfirmationSource(str, Enum):
    """Methodology or instrument used by the inspector to verify the physical condition."""
    VISUAL_INSPECTION = "VISUAL_INSPECTION"
    NON_DESTRUCTIVE_TESTING = "NON_DESTRUCTIVE_TESTING"
    ULTRASONIC_TESTING = "ULTRASONIC_TESTING"
    EDDY_CURRENT = "EDDY_CURRENT"
    MAGNETIC_PARTICLE = "MAGNETIC_PARTICLE"
    FIELD_MEASUREMENT = "FIELD_MEASUREMENT"
    HISTORICAL_RECORD = "HISTORICAL_RECORD"


class CorrectionType(str, Enum):
    """Structured classification of any human inspector correction applied to AI predictions."""
    NONE = "NONE"
    DEFECT_ABSENT = "DEFECT_ABSENT"
    DEFECT_MISCLASSIFIED = "DEFECT_MISCLASSIFIED"
    SEVERITY_OVERESTIMATED = "SEVERITY_OVERESTIMATED"
    SEVERITY_UNDERESTIMATED = "SEVERITY_UNDERESTIMATED"
    ACTION_MODIFIED = "ACTION_MODIFIED"
    MULTIPLE_CORRECTIONS = "MULTIPLE_CORRECTIONS"


class ReviewerCorrection(BaseModel):
    """Structured details of reviewer adjustments to AI predictions."""
    correction_type: CorrectionType = Field(default=CorrectionType.NONE, description="Classification of correction")
    corrected_severity: Optional[str] = Field(default=None, description="Human confirmed physical severity")
    corrected_defect_type: Optional[str] = Field(default=None, description="Human confirmed defect classification")
    corrected_action: Optional[str] = Field(default=None, description="Human confirmed operational action")
    justification: Optional[str] = Field(default=None, description="Technical engineering justification for correction")

    model_config = ConfigDict(extra="forbid")


class InspectionOutcomeCreate(BaseModel):
    """Inbound payload submitted by a human inspector to finalize an inspection review."""
    reviewer_id: str = Field(..., min_length=2, max_length=64, description="Unique identifier of the authorized human inspector")
    review_status: ReviewOutcomeStatus = Field(..., description="Human review disposition: APPROVED, CORRECTED, or REJECTED")
    confirmed_defect_present: bool = Field(..., description="Whether physical defect was confirmed to exist on the asset")
    confirmed_severity: str = Field(..., description="Confirmed physical severity: CRITICAL, HIGH, MEDIUM, LOW, or NONE")
    confirmed_defect_type: str = Field(..., description="Confirmed physical defect class or NONE")

    reviewer_correction: Optional[ReviewerCorrection] = Field(default=None, description="Structured correction payload if review_status is CORRECTED or REJECTED")
    reviewer_comment: Optional[str] = Field(default=None, max_length=2000, description="Observational notes from inspector (passive text data)")
    confirmation_source: ConfirmationSource = Field(default=ConfirmationSource.VISUAL_INSPECTION, description="Physical verification source")
    evidence_quality: EvidenceQuality = Field(default=EvidenceQuality.ADEQUATE, description="Evaluation of source visual evidence")

    model_config = ConfigDict(extra="forbid")


class AIPredictionSnapshot(BaseModel):
    """Immutable snapshot of the AI's predictions at the time of review."""
    ai_risk_score: int = Field(..., ge=0, le=100, description="Deterministic risk score generated by DecisionPolicyEngine")
    ai_severity: str = Field(..., description="AI predicted physical severity")
    ai_action: str = Field(..., description="AI formulated operational action")
    ai_risk_band: str = Field(..., description="AI risk band: CRITICAL, HIGH, MEDIUM, LOW")
    ai_defect_detected: bool = Field(..., description="Whether AI detected any defects")
    ai_defect_type: Optional[str] = Field(default=None, description="Primary defect class detected by AI")

    model_config = ConfigDict(extra="forbid")


class ConfirmedOutcomeSnapshot(BaseModel):
    """Immutable snapshot of the inspector-confirmed physical ground truth."""
    confirmed_defect_present: bool
    confirmed_severity: str
    confirmed_defect_type: str
    reviewer_correction: Optional[ReviewerCorrection] = None

    model_config = ConfigDict(extra="forbid")


class InspectionOutcomeResponse(BaseModel):
    """Authoritative representation of a persisted human review outcome."""
    id: int = Field(..., description="Internal surrogate ID")
    outcome_id: str = Field(..., description="Unique outcome record ID (out-xxx)")
    inspection_id: str = Field(..., description="Referenced inspection ID")
    asset_id: str = Field(..., description="Target industrial asset ID")
    component_id: Optional[str] = Field(default=None, description="Target component ID")
    reviewer_id: str = Field(..., description="Authorized reviewer identifier")
    review_status: ReviewOutcomeStatus = Field(..., description="Outcome classification")

    # Snapshots
    ai_prediction: AIPredictionSnapshot = Field(..., description="AI prediction snapshot")
    confirmed_outcome: ConfirmedOutcomeSnapshot = Field(..., description="Confirmed ground truth snapshot")

    # Metadata
    reviewer_comment: Optional[str] = None
    confirmation_source: ConfirmationSource
    evidence_quality: EvidenceQuality
    reviewed_at: datetime
    created_at: datetime

    # Evaluated flags
    is_agreement: bool = Field(..., description="True if AI predictions fully matched confirmed ground truth without corrections")

    model_config = ConfigDict(extra="forbid")


class InspectionOutcomeListResponse(BaseModel):
    """Paginated list of recorded inspection review outcomes."""
    total: int = Field(..., ge=0)
    items: List[InspectionOutcomeResponse] = Field(default_factory=list)

    model_config = ConfigDict(extra="forbid")
