"""Development-only PostgreSQL database seed script (Phase 2B + Phase 2D + Phase 3A).

IMPORTANT NOTICE:
All records generated by this script are SYNTHETIC DEVELOPMENT DATA created
for pipeline verification, testing, and agent development.
They DO NOT represent certified field records or real industrial facilities.
"""

from datetime import date, datetime, timezone
import json
from pathlib import Path
import sys

# Add project root to sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from backend.app.database.models.asset import Asset
from backend.app.database.models.component import Component
from backend.app.database.models.defect import DefectRecord
from backend.app.database.models.incident import IncidentRecord
from backend.app.database.models.inspection import InspectionRecord
from backend.app.database.models.maintenance import MaintenanceRecord
from backend.app.database.models.review import InspectionReview, ReviewAuditLog
from backend.app.database.models.work_order import WorkOrder
from backend.app.database.session import SessionLocal

SYNTHETIC_TAG = "development_synthetic"


def seed_database():
    db = SessionLocal()
    print("=== Seeding PostgreSQL Database with Synthetic Development Data ===")

    try:
        # 1. Clean existing synthetic records
        print("Cleaning previous synthetic test records...")
        db.query(ReviewAuditLog).delete()
        db.query(InspectionReview).delete()
        db.query(DefectRecord).delete()
        db.query(MaintenanceRecord).filter(MaintenanceRecord.source_type == SYNTHETIC_TAG).delete()
        db.query(InspectionRecord).filter(InspectionRecord.source_type == SYNTHETIC_TAG).delete()
        db.query(WorkOrder).filter(WorkOrder.source_type == SYNTHETIC_TAG).delete()
        db.query(IncidentRecord).filter(IncidentRecord.source_type == SYNTHETIC_TAG).delete()
        db.query(Component).filter(Component.source_type == SYNTHETIC_TAG).delete()
        db.query(Asset).filter(Asset.source_type == SYNTHETIC_TAG).delete()
        db.commit()

        # 2. Seed Assets
        print("Creating synthetic industrial assets...")
        asset_pl = Asset(
            asset_id="ASSET-PL-01",
            asset_code="PIPE-001",
            asset_type="PIPELINE",
            name="Crude Hydrocarbon Transmission Pipeline Loop 1A",
            manufacturer="Valourec Seamless Tubulars",
            model="API-5L-X65",
            serial_number="VLM-2021-9941",
            installation_date=date(2021, 4, 15),
            location="Sector 4 - High-Pressure Distribution Manifold",
            operational_status="OPERATIONAL",
            warranty_start=date(2021, 4, 15),
            warranty_end=date(2031, 4, 15),
            source_type=SYNTHETIC_TAG
        )
        asset_tk = Asset(
            asset_id="ASSET-TK-04",
            asset_code="TANK-004",
            asset_type="STORAGE_TANK",
            name="Atmospheric Hydrocarbon Storage Tank 04",
            manufacturer="CBI Industrial Tankage",
            model="API-650-FLT",
            serial_number="CBI-2018-0412",
            installation_date=date(2018, 9, 1),
            location="Terminal Tank Farm - Area B",
            operational_status="OPERATIONAL",
            warranty_start=date(2018, 9, 1),
            warranty_end=date(2028, 9, 1),
            source_type=SYNTHETIC_TAG
        )
        asset_struct = Asset(
            asset_id="ASSET-ST-12",
            asset_code="STRUCT-012",
            asset_type="STRUCTURAL_FRAME",
            name="Heavy Pipe Rack Structural Support Frame 12",
            manufacturer="Nucor Heavy Steels",
            model="AISC-W14x90",
            serial_number="NUC-2019-1102",
            installation_date=date(2019, 6, 20),
            location="Offshore Berth Loading Gantry",
            operational_status="OPERATIONAL",
            warranty_start=date(2019, 6, 20),
            warranty_end=date(2029, 6, 20),
            source_type=SYNTHETIC_TAG
        )
        asset_pump = Asset(
            asset_id="ASSET-PU-07",
            asset_code="PUMP-007",
            asset_type="ROTATING_EQUIPMENT",
            name="High-Pressure Main Feed Booster Pump Unit 07",
            manufacturer="Flowserve Pump Division",
            model="HDX-6x13-2S",
            serial_number="FLS-2020-5542",
            installation_date=date(2020, 1, 10),
            location="Booster Pump Station Alpha",
            operational_status="OPERATIONAL",
            warranty_start=date(2020, 1, 10),
            warranty_end=date(2025, 1, 10),
            source_type=SYNTHETIC_TAG
        )
        db.add_all([asset_pl, asset_tk, asset_struct, asset_pump])
        db.flush()

        # 3. Seed Components
        print("Creating synthetic inspectable components...")
        comp1 = Component(
            component_id="PIPE-SEG-4021",
            asset_id="ASSET-PL-01",
            component_type="PIPE_SEGMENT",
            name="Primary Body Segment 4021 (Span 40m - 52m)",
            material="CARBON_STEEL_A106_GR_B",
            location_description="Above-ground pipeline rack, Bay 12",
            installation_date=date(2021, 4, 20),
            status="NORMAL",
            source_type=SYNTHETIC_TAG
        )
        comp2 = Component(
            component_id="PIPE-WELD-4022",
            asset_id="ASSET-PL-01",
            component_type="WELD_SEAM",
            name="Circumferential Girth Weld 4022",
            material="ER70S-6_FILLER",
            location_description="Between Segments 4021 and 4023",
            installation_date=date(2021, 4, 22),
            status="NORMAL",
            source_type=SYNTHETIC_TAG
        )
        comp3 = Component(
            component_id="PIPE-FLG-4023",
            asset_id="ASSET-PL-01",
            component_type="FLANGE",
            name="Class 600 Raised Face Flange Joint 4023",
            material="STAINLESS_STEEL_316L",
            location_description="Isolation Valve Intake Flange",
            installation_date=date(2021, 4, 25),
            status="NORMAL",
            source_type=SYNTHETIC_TAG
        )
        comp4 = Component(
            component_id="TANK-SHELL-101",
            asset_id="ASSET-TK-04",
            component_type="TANK_SHELL",
            name="Lower Shell Course Tier 1",
            material="CARBON_STEEL_A36",
            location_description="Tank 04 North Perimeter Wall",
            installation_date=date(2018, 9, 5),
            status="NORMAL",
            source_type=SYNTHETIC_TAG
        )
        comp5 = Component(
            component_id="STRUCT-BEAM-301",
            asset_id="ASSET-ST-12",
            component_type="SUPPORT_BEAM",
            name="Transverse Cantilever Beam 301",
            material="STRUCTURAL_STEEL_A992",
            location_description="Pipe Rack Gantry Tier 2",
            installation_date=date(2019, 6, 22),
            status="NORMAL",
            source_type=SYNTHETIC_TAG
        )
        db.add_all([comp1, comp2, comp3, comp4, comp5])
        db.flush()

        # 4. Seed Maintenance Records
        print("Creating synthetic maintenance records...")
        maint1 = MaintenanceRecord(
            maintenance_id="MAINT-2023-0144",
            component_id="PIPE-SEG-4021",
            maintenance_type="PREVENTIVE_MAINTENANCE",
            performed_at=datetime(2023, 3, 10, 8, 30, tzinfo=timezone.utc),
            description="Routine scheduled ultrasonic wall thickness survey.",
            findings="Nominal wall thickness 12.7mm measured. No active corrosion loss detected.",
            action_taken="Survey completed and logged. Next scheduled survey set for Q1 2024.",
            technician_team="Pipeline Integrity Team Alpha",
            downtime_hours=0.0,
            cost=1200.00,
            source_type=SYNTHETIC_TAG
        )
        maint2 = MaintenanceRecord(
            maintenance_id="MAINT-2024-0891",
            component_id="PIPE-SEG-4021",
            maintenance_type="COATING",
            performed_at=datetime(2024, 8, 22, 14, 0, tzinfo=timezone.utc),
            description="Surface preparation and protective barrier coating re-application.",
            findings="Minor exterior surface oxidation observed on upper pipe curvature.",
            action_taken="Sandblasted to Sa 2.5 standard; applied two coats of high-build epoxy.",
            technician_team="Surface Protection Specialists",
            downtime_hours=4.5,
            cost=3450.00,
            source_type=SYNTHETIC_TAG
        )
        db.add_all([maint1, maint2])

        # 5. Seed Historical Inspections
        print("Creating synthetic historical inspection records...")
        insp1 = InspectionRecord(
            inspection_id="INSP-2023-0912",
            component_id="PIPE-SEG-4021",
            inspection_timestamp=datetime(2023, 9, 12, 11, 15, tzinfo=timezone.utc),
            inspection_method="MANUAL_VISUAL",
            defect_type="none",
            severity="LOW",
            confidence=0.95,
            findings="Annual visual inspection: external coating intact, no mechanical damage.",
            evidence_reference="reports/2023/insp-0912-audit.pdf",
            model_name="Manual Inspection",
            model_version="N/A",
            source_type=SYNTHETIC_TAG
        )
        insp2 = InspectionRecord(
            inspection_id="INSP-2024-0404",
            component_id="PIPE-SEG-4021",
            inspection_timestamp=datetime(2024, 4, 4, 15, 45, tzinfo=timezone.utc),
            inspection_method="AUTONOMOUS_VISION",
            defect_type="crack",
            severity="MEDIUM",
            confidence=0.78,
            findings="Autonomous crawler detected minor surface hairline indication near upper quadrant.",
            evidence_reference="experiments/vision/deepcrack/inference/evidence/11112.evidence.json",
            model_name="YOLO11n-seg",
            model_version="1.0.0",
            source_type=SYNTHETIC_TAG
        )
        insp3 = InspectionRecord(
            inspection_id="insp-11112-44e62c64",
            component_id="PIPE-SEG-4021",
            inspection_timestamp=datetime(2026, 8, 31, 14, 0, tzinfo=timezone.utc),
            inspection_method="AUTONOMOUS_VISION",
            defect_type="crack",
            severity="CRITICAL",
            confidence=0.88,
            findings="Critical multi-region surface crack indication detected across high-pressure segment.",
            evidence_reference="experiments/vision/deepcrack/inference/evidence/11112.evidence.json",
            model_name="YOLO11n-seg",
            model_version="1.0.0",
            source_type=SYNTHETIC_TAG
        )
        db.add_all([insp1, insp2, insp3])

        # 6. Seed Normalized Defect Records (Phase 3A)
        print("Creating synthetic normalized defect records...")
        def1 = DefectRecord(
            defect_id="def-2024-0404-01",
            inspection_id="INSP-2024-0404",
            asset_id="ASSET-PL-01",
            component_id="PIPE-SEG-4021",
            defect_type="crack",
            confidence=0.78,
            affected_area_percentage=1.20,
            bounding_box_area_percentage=3.10,
            crack_length_pixels=140.0,
            crack_width_estimate_pixels=8.5,
            location_type="UPPER_QUADRANT",
            detection_timestamp=datetime(2024, 4, 4, 15, 45, tzinfo=timezone.utc),
            raw_evidence_detection_id="det-001",
            source_type=SYNTHETIC_TAG
        )
        def2 = DefectRecord(
            defect_id="def-2026-0831-01",
            inspection_id="insp-11112-44e62c64",
            asset_id="ASSET-PL-01",
            component_id="PIPE-SEG-4021",
            defect_type="crack",
            confidence=0.638,
            affected_area_percentage=4.55,
            bounding_box_area_percentage=8.20,
            crack_length_pixels=648.3,
            crack_width_estimate_pixels=14.7,
            location_type="LONGITUDINAL_BODY",
            detection_timestamp=datetime(2026, 8, 31, 14, 0, tzinfo=timezone.utc),
            raw_evidence_detection_id="det-001",
            source_type=SYNTHETIC_TAG
        )
        def3 = DefectRecord(
            defect_id="def-2026-0831-02",
            inspection_id="insp-11112-44e62c64",
            asset_id="ASSET-PL-01",
            component_id="PIPE-SEG-4021",
            defect_type="crack",
            confidence=0.351,
            affected_area_percentage=4.43,
            bounding_box_area_percentage=7.90,
            crack_length_pixels=412.0,
            crack_width_estimate_pixels=11.2,
            location_type="LONGITUDINAL_BODY",
            detection_timestamp=datetime(2026, 8, 31, 14, 0, tzinfo=timezone.utc),
            raw_evidence_detection_id="det-002",
            source_type=SYNTHETIC_TAG
        )
        db.add_all([def1, def2, def3])

        # 7. Seed Historical Work Orders
        print("Creating synthetic work orders...")
        wo1 = WorkOrder(
            work_order_id="WO-2024-0418",
            component_id="PIPE-SEG-4021",
            inspection_id="INSP-2024-0404",
            priority="MEDIUM",
            status="COMPLETED",
            recommended_action="Execute localized high-frequency eddy current verification and apply epoxy seal.",
            assigned_team="Rapid Maintenance Unit 3",
            created_at=datetime(2024, 4, 5, 9, 0, tzinfo=timezone.utc),
            completed_at=datetime(2024, 4, 8, 16, 30, tzinfo=timezone.utc),
            estimated_cost=2500.0,
            actual_cost=2380.0,
            downtime_hours=2.0,
            source_type=SYNTHETIC_TAG
        )
        wo2 = WorkOrder(
            work_order_id="WO-2026-0831",
            component_id="PIPE-SEG-4021",
            inspection_id="insp-11112-44e62c64",
            priority="CRITICAL",
            status="PENDING_APPROVAL",
            recommended_action="Perform Ultrasonic Thickness Measurement and Crack Detection Survey on Segment 4021.",
            assigned_team="Pipeline Structural Integrity Team",
            created_at=datetime(2026, 8, 31, 14, 30, tzinfo=timezone.utc),
            completed_at=None,
            estimated_cost=4000.0,
            actual_cost=None,
            downtime_hours=8.0,
            source_type=SYNTHETIC_TAG
        )
        db.add_all([wo1, wo2])

        # 8. Seed Relevant Incidents
        print("Creating synthetic historical failure incidents...")
        inc1 = IncidentRecord(
            incident_id="INC-2022-044",
            component_type="PIPE_SEGMENT",
            defect_type="crack",
            description="Longitudinal surface crack propagation caused by heavy cyclic vibration from upstream booster pump.",
            root_cause="Pump support damper degradation resulting in harmonic fatigue resonance.",
            corrective_action="Replaced pipe section; installed dynamic vibration dampener dampers.",
            severity="HIGH",
            occurred_at=datetime(2022, 6, 14, 18, 0, tzinfo=timezone.utc),
            resolved_at=datetime(2022, 6, 17, 12, 0, tzinfo=timezone.utc),
            source_type=SYNTHETIC_TAG
        )
        inc2 = IncidentRecord(
            incident_id="INC-2023-108",
            component_type="WELD_SEAM",
            defect_type="crack",
            description="Circumferential weld toe cracking detected during hydro-test.",
            root_cause="Inadequate post-weld heat treatment causing localized residual stress concentration.",
            corrective_action="Girth weld ground out, reweld with pre-heat and verified PWHT protocol.",
            severity="CRITICAL",
            occurred_at=datetime(2023, 11, 2, 8, 30, tzinfo=timezone.utc),
            resolved_at=datetime(2023, 11, 6, 20, 0, tzinfo=timezone.utc),
            source_type=SYNTHETIC_TAG
        )
        db.add_all([inc1, inc2])

        # 9. Seed Inspection Reviews & Audit Logs
        print("Creating synthetic human-in-the-loop inspection reviews...")
        rev1 = InspectionReview(
            review_id="rev-insp-11112-44e62c64-PIPE-SEG-4021",
            inspection_id="insp-11112-44e62c64",
            asset_id="ASSET-PL-01",
            component_id="PIPE-SEG-4021",
            assessment_id="assess-insp-11112-44e62c64-PIPE-SEG-4021",
            status="PENDING_HUMAN_REVIEW",
            priority="CRITICAL",
            reviewer_id=None,
            reviewer_name=None,
            reviewer_comments=None,
            original_vision_evidence={"source_image_filename": "11112.jpg", "blur_score": 150.0},
            original_decision={"priority": "CRITICAL", "confidence": "HIGH"},
            original_assessment={
                "summary": "Visual inspection identified multiple crack detections on Primary Body Segment 4021.",
                "detected_defects": [
                    {"detection_id": "det-001", "defect_type": "crack", "confidence": 0.638, "affected_area_percentage": 4.55},
                    {"detection_id": "det-002", "defect_type": "crack", "confidence": 0.351, "affected_area_percentage": 4.43}
                ],
                "historical_context_summary": "Prior coating maintenance in 2024.",
                "reasoning": "Crack detections exceed critical spatial span threshold.",
                "risk_factors": ["Cyclic Loading", "Fatigue Crack Propagation"],
                "recommended_actions": ["Detailed NDE Inspection"],
                "confidence": "MEDIUM",
                "uncertainty": "Visual surface perception only.",
                "source_references": {"source_image_filename": "11112.jpg", "is_synthetic_data": True}
            },
            original_draft_work_order={
                "priority": "CRITICAL",
                "recommended_action": "Conduct Ultrasonic Thickness Testing and MPI.",
                "justification": "Surface crack indication.",
                "required_inspection": "Ultrasonic NDE",
                "suggested_team": "Pipeline Structural Integrity Team",
                "estimated_downtime_hours": 8.0,
                "estimated_cost": 4000.0,
                "uncertainty": "Visual data uncertainty",
                "approval_status": "PENDING_HUMAN_REVIEW"
            },
            reasoning_trace={
                "input_evidence_references": {"source_image_filename": "11112.jpg"},
                "deterministic_decision_reference": {"priority": "CRITICAL"},
                "provider": "ollama",
                "model": "gemma3:latest"
            },
            edited_work_order=None,
            reviewed_at=None
        )
        db.add(rev1)
        db.flush()

        aud1 = ReviewAuditLog(
            audit_id="aud-init-001",
            review_id=rev1.review_id,
            event_type="REVIEW_CREATED",
            previous_status=None,
            new_status="PENDING_HUMAN_REVIEW",
            change_summary="Autonomous inspection assessment received and initialized for human review.",
            created_at=datetime.now(timezone.utc)
        )
        db.add(aud1)

        db.commit()
        print("\n[OK] Database successfully seeded with synthetic development records.")
        print("  Assets Seeded:          4")
        print("  Components Seeded:      5")
        print("  Maintenance Records:    2")
        print("  Inspection Records:     3")
        print("  Defect Records:         3")
        print("  Work Orders:            2")
        print("  Incident Records:       2")
        print("  Inspection Reviews:     1")

    except Exception as e:
        db.rollback()
        print(f"Error seeding database: {e}", file=sys.stderr)
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_database()
