"""Pydantic schemas for LLM provider abstraction layer."""

from typing import Any, Dict, Optional
from pydantic import BaseModel, ConfigDict, Field


class LLMGenerationRequest(BaseModel):
    """Input parameters for LLM text generation."""
    prompt: str = Field(..., description="Complete structured prompt string")
    system: Optional[str] = Field(default=None, description="Optional system instruction")
    temperature: float = Field(default=0.1, ge=0.0, le=1.0, description="Sampling temperature (low for deterministic reasoning)")
    format: Optional[str] = Field(default="json", description="Enforce JSON structured output mode")
    max_tokens: Optional[int] = Field(default=2048, description="Maximum generated token budget")

    model_config = ConfigDict(extra="forbid")


class LLMGenerationResponse(BaseModel):
    """Normalized response returned from LLM provider."""
    text: str = Field(..., description="Raw text or JSON generated by the model")
    model: str = Field(..., description="Model identifier that produced the completion")
    duration_ms: float = Field(..., description="Generation execution latency in milliseconds")
    prompt_tokens: Optional[int] = Field(default=None)
    completion_tokens: Optional[int] = Field(default=None)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    model_config = ConfigDict(extra="forbid")


class LLMHealthStatus(BaseModel):
    """Health check status for the active LLM provider."""
    provider: str = Field(..., description="LLM provider name (e.g. 'ollama')")
    model: str = Field(..., description="Target model name (e.g. 'gemma3:latest')")
    available: bool = Field(..., description="True if local provider is reachable and model is loaded")
    details: Optional[str] = Field(default=None, description="Diagnostic message or error description")

    model_config = ConfigDict(extra="forbid")
